project:
  type: website
  # output-dir: "docs"

execute:
  freeze: auto

website:
  title: "SM-2302 Special Lectures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 1-scraping_linear_reg.qmd
        text: Scraping and Linear Regression

format:
  html:
    toc: true

bibliography: refs.bib



