project:
  type: book
  output-dir: "docs"

execute:
  freeze: auto

# website:
#   title: "SM-2302 Special Lectures"
#   navbar:
#     left:
#       - href: index.qmd
#         text: Home
#       - href: 1-scraping_linear_reg.qmd
#         text: Scraping and linear regression
#       - href: 2-gis_data.qmd
#         text: Spatial data analysis
#       - href: 3-quanteda.qmd
#         text: Quantitative text analysis

book:
  title: "SM-2302 Special Lectures"
  author: "Dr. Haziq Jamil"
  chapters:
    - index.qmd
    - 1-scraping_linear_reg.qmd
    - 2-gis_data.qmd
    - 3-quanteda.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreprt

bibliography: refs.bib



